project:
  type: website

website:
  title: "My lab notebook"
  navbar:
    background: "#4A7862"
    foreground: "#F3F3EE"
    search: true
    left:
      - weekly-notes/index.qmd
      - reading-notes/index.qmd
      - meetings.qmd
      - text: "Projects"
        menu: 
        - projects/how-to.qmd 
        - projects/project-1/index.qmd
    sidebar:  
      contents: auto
format: 
  html:  
    theme: cosmo
    css: styles.css 
    toc: true
    linkcolor: "#4A7862"
    backgroundcolor: "#faf8f6"
