---
title: "2025 Spring BIOL 1208"
projects: biol1208
---

## 2025-01-10 

*I missed this prep meeting because of my International Student Orientation*

## 2025-01-17

- School closure possible next week due to winter storm predictions
	- Inform students of due dates in pre-week email: Syllabus and Safety quiz still due by 27th even if school closes, while other ICA will be pushed (all classes and schedule in general will be pushed forward by 1 week)
- For pre-lab quizzes, which TAs cannot open and view, if anyone emails saying they missed the deadline, forward the request to Dr B because she can heck if they’re lying (we can see their activity log on Moodle)
- **Do not** share grades with anyone except the student. In exceptional cases, forward to Dr B and mention that Student Advisory board can provide an authorization form.

- In Scientific Methods **only**, they can use AI for the ICAs. **Ensure they are aware that they cannot use AI in any of the other assignments.**
	- They need to: choose a topic (from the list provided), give a prompt to create a biological case study in __ field; rest should all be done by themselves (coming up with questions, hypotheses, predictions, etc.
	- The AI demo video is available in the PPT only in the instructor version, but students can find it in “Lecture videos” on Moodle.
- Emphasise that even if we TAs go through in class and help students (even if suggest corrections), doesn’t guarantee 100% grade; tell them there’s a reason grading is done completely separately and not in class.
- Template for ICA is available on Moodle, which they can download and edit.

## 2025-01-24

**Grading**

- Don’t go via “Grade” button on first page; click the “View all submission” instead; then the “GradeMark” pencil button for each student to open Turnitin rubrics etc.
- It is fine if total grade comes to >100%, like with bonus points

## 2025-01-31

### Geaux Communicate (Becky Carmichael, Negar Basiri)

**Feedback and Culture: Audience and Language**

- Communicate with cultural competency

When an instructor noticed an assignment of yours and responded on its qualities… Can’t remember a specific instance, but some important points: 

- Not focusing on the grading so much as on the content and feedback on what can be improved
- Even if something is wrong, treating it respectfully and trying to compare and contextualise with what is right
- Treating uncertainties positively / admitting their own uncertainty
- *Connection*

What are your current feedback strategies?
- Using “should”, “must”, etc. sparingly
- Giving positive feedback as well
- Providing adequate reasoning for feedback

- “[NAME], please …”

Let’s establish a common language:
- Define key terms
- Review rubric
- Provide and discuss a Common Mistakes document
- Annotate assignments to demonstrate feedback language
- Share a respond-to-feedback template

C-I Teaching Toolkit available

### Prep

- After Techniques review, go over lab forecast, emphasis on Partial Lab Report in all Enzymes classes—writing, DON’T COPY

## 2025-02-07

...

## 2025-02-21

- TAs should leave SAA cases ungraded, Dr B will handle soon
- Review should go only for max 1 hour (inc. student presentations ideally 3—index cards/PPT and bar graph by hand on board)
- Mid-term should start 1 hour after class start time
	- Those who scheduled with ODS TC can leave after the presentation because exam will be separate (and graded by Dr B)
- Switch off all electronics, no headphones—even better, remove and keep in bag
- Write names and sections legibly on midterm paper
- DO NOT write anything on word banks because we collect them back, and they’re supposed to be a reference for the fill-in-the-blank questions
	- There’ll be separate rough sheets for calculations, or can even use blank space in the end of the test booklet

## 2025-03-21

- Very long experiment, don’t allow more than 1 repeat (ideally no repeats)
    - Extracts cannot be easily prepared, unlike last class with blood
- No rinsing needed this time since acetone will evaporate; only real discard is capillary tubes, rest in discard bottles near sink
- To troubleshoot, give the chromatography solution a whiff: acetone smells like nail polish remover, solvent smells like gas—so check for more acetone
- Leave doors open, can open hallway windows, can even try turning on fan above fridge
- Keep ensuring chrom. jar are closed (esp. after they take out chrom. paper)
- For 209, extra solvent is in 214, yellow cabinet
- 4 mL is how much is required in cuvette to get spec. reading
- On chrom. paper, start the lines 3 cm from the end (jar needs 1 cm height of solvent)

## 2025-04-11

- Come early (~15 min) to pour agarose gel so that they solidify during lecture, and to organise plasmid tubes into racks in fridge
    - Each tray ~ 12.5 mL (don’t overpour)
    - Use pipette but immediately rinse with hot water
    - Put agarose flask back in incubator
- Allow them to hold gel with hands and place in rack

## Feedback

The majority of feedback for us TAs was positive, and students particularly liked that we were approachable and open to questions in class and over email. 

Below are some common points of constructive criticism from students (particularly my section 26):

- Grading: unfair(?), lateness (but this was just 1--2 students)
- Lecturing: backtracking & repeating what already explained (one student)

And specifically for the course elements:

- Need more detailed walkthrough of writing lab reports (maybe more examples of right vs wrong)
- Good to guide through how they can relate Enzymes labs to lab reports and also their respective fields
- Need more time between PLR grading and FLR submission
- We should review polarity & chromatography in more detail
    - Flash cards not helpful for this specifically